### ISSUE TITLE
Create form to search for location

### ISSUE THREAD

**Issue by aturkewi** [bradleyjay/youre_better_than_this#2]
This will be our initial index page a `/`
It will have a text box for name
It will have a text box for 

- [X] Create a form at `/`
- [x] Catch POST request
- [x] Print the data to the console on the back end to prove we got it
- [ ] Redirect user to a page with their data

**Comment by bradleyjay** [comment]
Completed - [Catch POST request], [Print data to console]. Now, need a parser function. After that, to pass  the parsed data back to user's browser.
